import{patch}from'../core/state.js';
export function watchPosts(){const ref=window.db.ref('posts').orderByChild('status').equalTo('published');const fn=s=>{const d=s.val()||{};const posts=Object.values(d).sort((a,b)=>Date.parse(b.publishedAt||b.createdAt||0)-Date.parse(a.publishedAt||a.createdAt||0));patch({posts});};ref.on('value',fn);return()=>ref.off('value',fn)}
export function loadOfficialFallback(){if(!window.fetch)return()=>{};let cancelled=false;fetch('./data/official-news.json').then(r=>r.ok?r.json():[]).then(items=>{if(cancelled)return;const current=window.__SKIPPER_STATE_REF?.();if(!current?.posts?.length)patch({posts:items.sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt))});}).catch(()=>{});return()=>{cancelled=true;}}
export function watchProfiles(){const ref=window.db.ref('publicProfiles');const fn=s=>{const p=s.val()||{};const online=Object.values(p).filter(x=>x?.lastSeenAt&&Date.now()-Date.parse(x.lastSeenAt)<5*60000&&x.status!=='suspended').length;patch({profiles:p,onlineCount:online});};ref.on('value',fn);return()=>ref.off('value',fn)}
export function listenNotifications(uid){const ref=window.db.ref(`notifications/${uid}`).limitToLast(60);const fn=s=>{const n=Object.entries(s.val()||{}).map(([id,v])=>({id,...v})).sort((a,b)=>Date.parse(b.createdAt||0)-Date.parse(a.createdAt||0));patch({notifications:n});};ref.on('value',fn);return()=>ref.off('value',fn)}
export function watchSystem(){const ref=window.db.ref('system');const fn=s=>patch({system:s.val()||{}});ref.on('value',fn);return()=>ref.off('value',fn)}
export function watchForumThreads(){const ref=window.db.ref('forumThreads').orderByChild('updatedAt');const fn=s=>{const rows=Object.entries(s.val()||{}).map(([id,v])=>({id,...v})).filter(x=>x.status==='published').sort((a,b)=>Date.parse(b.updatedAt||b.createdAt||0)-Date.parse(a.updatedAt||a.createdAt||0));patch({forumThreads:rows});};ref.on('value',fn);return()=>ref.off('value',fn)}

export const publishPost=payload=>import('./api.js').then(({call})=>call('createPost',payload));
export const addComment=(postId,text)=>import('./api.js').then(({call})=>call('addComment',{postId,text}));
export const markAllNotificationsRead=uid=>import('./api.js').then(async({call})=>{const s=window.__SKIPPER_STATE_REF?.();for(const n of (s?.notifications||[]).filter(x=>!x.read))await call('markNotificationRead',{id:n.id});});
export function watchComments(postId,cb){const ref=window.db.ref(`comments/${postId}`).limitToLast(100);const fn=s=>{const items=Object.entries(s.val()||{}).map(([id,v])=>({id,...v})).sort((a,b)=>Date.parse(a.createdAt||0)-Date.parse(b.createdAt||0));window.__skipperComments=items;cb(items)};ref.on('value',fn);return()=>ref.off('value',fn);}
export function watchLikeCount(postId,cb){const ref=window.db.ref(`postStats/${postId}/likes`);const fn=s=>cb(Number(s.val()||0));ref.on('value',fn);return()=>ref.off('value',fn);}
export function watchCommentCount(postId,cb){const ref=window.db.ref(`comments/${postId}`);const fn=s=>cb(Object.keys(s.val()||{}).length);ref.on('value',fn);return()=>ref.off('value',fn);}
export function watchLikeState(postId,uid,cb){const ref=window.db.ref(`postReactions/${postId}/${uid}`);const fn=s=>cb(s.exists());ref.on('value',fn);return()=>ref.off('value',fn);}
export const toggleLike=(postId,uid)=>import('./api.js').then(({call})=>call('togglePostReaction',{postId,reaction:'like'}));
