import{initAuth,startPresence}from'./services/auth.js';import{watchPosts,watchProfiles,listenNotifications,watchSystem,watchForumThreads,loadOfficialFallback}from'./services/data.js';import{getState,subscribe,patch}from'./core/state.js';import{initRouter,bindRouter}from'./core/router.js';import{shell}from'./ui/layout.js';import{toast}from'./ui/toast.js';import{renderModal,bindModalActions,destroyModalBindings}from'./ui/modal.js';import{home}from'./modules/home.js';import{renderFeed,bindFeed,destroyFeed}from'./modules/feed.js';import{forum,bindForum}from'./modules/forum.js';import{crew,bindCrew}from'./modules/crew.js';import{messages,bindMessages,destroyMessages}from'./modules/messages.js';import{games,bindGames}from'./modules/games.js';import{profile}from'./modules/profile.js';import{settings,bindSettings}from'./modules/settings.js';
const app=document.getElementById('app');window.__SKIPPER_STATE_REF=()=>getState();let stops=[];let renderQueued=false;let lastRoute=null;
const renderers={home,feed:renderFeed,forum,crew,messages,games,profile,settings};
function render(){renderQueued=false;const s=getState();if(lastRoute==='messages'&&s.route!=='messages')destroyMessages();if(lastRoute==='feed'&&s.route!=='feed')destroyFeed();lastRoute=s.route;app.innerHTML=s.authMode==='error'?errorView(s):shell((renderers[s.route]||home)());const overlay=document.getElementById('overlay');if(overlay)overlay.innerHTML=renderModal();bindCurrent();bindModalActions();}
function errorView(s){return `<div class="fatal"><div>⚠</div><h1>Не удалось войти</h1><p>${s.authError||'Ошибка авторизации'}</p><button class="btn primary" onclick="location.reload()">Повторить</button><button class="btn ghost" id="guestFallback">Продолжить без аккаунта</button></div>`}
function bindCurrent(){bindRouter(app);if(lastRoute==='feed')bindFeed();if(lastRoute==='forum')bindForum?.();if(lastRoute==='crew')bindCrew?.();if(lastRoute==='messages')bindMessages?.();if(lastRoute==='games')bindGames?.();if(lastRoute==='settings')bindSettings?.();app.querySelector('[data-login]')?.addEventListener('click',()=>toast('Откройте Mini App внутри Telegram, чтобы войти.','info'));app.querySelector('#guestFallback')?.addEventListener('click',()=>{sessionStorage.setItem('skipper_guest','1');location.reload();});const crewSearch=app.querySelector('#crewSearch');if(crewSearch)crewSearch.oninput=e=>patch({crewQuery:e.target.value});const n=app.querySelector('[data-notifications]');if(n)n.onclick=()=>toast(`${getState().notifications.filter(x=>!x.read).length} непрочитанных уведомлений`,'info');}
subscribe(()=>{if(renderQueued)return;renderQueued=true;queueMicrotask(render)});initRouter();
(async()=>{const user=await initAuth();stops=[watchPosts(),watchProfiles(),watchSystem(),watchForumThreads(),loadOfficialFallback()];if(user){stops.push(listenNotifications(user.id));stops.push(startPresence(user.id));}render();})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('beforeunload',()=>{stops.forEach(s=>s?.());destroyMessages();destroyFeed();destroyModalBindings();});
